In [ ]:
#polymorphism 
one name different work
overload clss ke under 2 work


In [6]:
class multiply():
    def __init__(self a,b,c=1):
        self.a=a
        self.b=b
        self.c=c
    def mul(self):
        return self.a*self.b*self.c

class math(multiply):
    def __init_c (self a,b,c=1):
        multiply.__init__ (self a,b,c)
    def mul(self):
        print("multiplying 3 number",self.a*self.b*self.c)
    
multi = multiply(4,2)
multi.mul()
multi2 = multiply(4,2,6)
multi.mul()
m = math(5,3,20)
m.mul()



    
        
        


SyntaxError: invalid syntax (2735146839.py, line 2)

In [ ]:
#encapsulation
class ke data and metHOD BIND in objective
bind conndition,public,protected,private
#abstractuon

In [ ]:
#abstaction,
data hiding

In [11]:
from abc import ABC,abstractmethod
class multiply(ABC):
    @abstractmethod
    def mul(self):
        pass
class math(multiply):
    def __init__(self ,a,b):
        self.a=a
        self.b=b
    def mul(self):
       print("multipication of a and b is",self.a *self.b)
m = math(2,5)
m. mul()

    

multipication of a and b is 10


In [ ]:

#### excercise


In [ ]:
#vehicle class
form abc import ABC,abstractmethod
class vehicle (ABC):
    @abstractmethod
    def fuel(self):
        pass
    def wheel(self):
        pass
class bus(vehicle0):
    def fuel (self):
        print("diesal")
    def petrol(self):
        print("petrol"

#Try and except



In [3]:
try:
    a=int(input("enter a number"))
    b=int(input("ennter a number"))
    c=a/b
    print(c)
except ZeroDivisionzerror: 
    print("you have entered demoninator as zero")
except vallueerror:
    print("you are converting text into int")
except exception:
    print("there is somting wrong that i'm unnable to find")
finally:
    print("succefull code complete")
          

enter a number 5
ennter a number 2


2.5
succefull code complete


In [14]:
try:
     d={"user":1234,"pass":"@123"}
     d["users"]
except KeyError:
     print("there is wrong key")
    




there is wrong key


#### File handling

In [16]:
with open("hello.tax","w")as file:
    file.write("lecture & file handling")


In [26]:
##MODULE
import math
print(math.factorial(69))
print(math.sqrt(49))

171122452428141311372468338881272839092270544893520369393648040923257279754140647424000000000000000
7.0


In [27]:
import time
print(time.localtime())

time.struct_time(tm_year=2024, tm_mon=3, tm_mday=18, tm_hour=16, tm_min=32, tm_sec=10, tm_wday=0, tm_yday=78, tm_isdst=0)


In [29]:
import datetime
help(datetime)

Help on module datetime:

NAME
    datetime - Fast implementation of the datetime type.

MODULE REFERENCE
    https://docs.python.org/3.12/library/datetime.html

    The following documentation is automatically generated from the Python
    source files.  It may be incomplete, incorrect or include features that
    are considered implementation detail and may vary between Python
    implementations.  When in doubt, consult the module reference at the
    location listed above.

CLASSES
    builtins.object
        date
            datetime
        time
        timedelta
        tzinfo
            timezone

    class date(builtins.object)
     |  date(year, month, day) --> date object
     |
     |  Methods defined here:
     |
     |  __add__(self, value, /)
     |      Return self+value.
     |
     |  __eq__(self, value, /)
     |      Return self==value.
     |
     |  __format__(...)
     |      Formats self with strftime.
     |
     |  __ge__(self, value, /)
     |      Return sel

In [ ]:
import datetime
t_day =datetime date.today()
b_day =datetime date.date(2.9.2003)


In [10]:
#############OOPS
#calss
class car:
    color = "red"
    brand = "mercedes"
#objective
car1 = car()
print(car1.color)
print(car1.brand)



red
mercedes


In [5]:
class student:
    name = "manoj kumar"
    def __init__(self):
      print("adding new student in database")
## creating objective(instance)
s1 = student()
print(s1.name)



adding new student in database
manoj kumar


In [3]:
class student:
    name = "manas kumar"
    def __init__(self,fullname):
        self.name = fullname
        print("adding new student in database")
## creating objective(instance)
s1 = student("aman")
print(s1.name)

s2 = student("manoj")
print(s2.name)

adding new student in database
aman
adding new student in database
manoj


In [5]:
class student:
    name = "manas kumar"
    def __init__(self,fullname,marks):
        self.name = fullname
        self.marks = marks
        print("adding new student in database")
## creating objective(instance)
s1 = student("aman",95)
print(s1.name,s1.marks)

s2 = student("manoj",88)
print(s2.name,s2.marks)

adding new student in database
aman 95
adding new student in database
manoj 88


In [14]:
#####ENCAPSULATION
class student:
    college_name = "ABC college"

    def __init__(self,name,marks):
        self.name = name
        self.marks = marks

    def welcome(self):
        print("welcome student",self.name)

    def get_marks(self):
        print(self.maeks)

s1 = student("karan",97)
s1.welcome()
print(s1.get_marks)

welcome student karan
<bound method student.get_marks of <__main__.student object at 0x000001898A53F860>>


In [ ]:
##########create student class that take name & marks of 3 subject as argument in constructor. Then create a method to print the average.


In [31]:
class student:
    def __init__(self,name ,marks):
        self.name = name
        self.marks = marks

    def get_avg(self):
        sum = 0
        for value in self.marks:
            sum +=value
        print("hi",self.name,"your avg score  is:",sum/3)

s1 = student("monu",[99,95,56])
s1.get_avg()


             

hi monu your avg score  is: 83.33333333333333


In [35]:
##########ABSTRACTION
class car:
    def __init__(self):
        self.acc = False
        self.brk =False
        self.clutch =False

    def start(self):
        self.clutch = True
        self.acc = True
        print("car start")

car1 = car()
car1.start()

car start


In [ ]:
#########Create Account class with 2 attribute balance &acount no. Create method for debit ,credit & printing the balance .



In [51]:
class Account:
    def __init__(self,bal,acc):
        self.balance =bal
        self.account_no =acc

    def debit(self,amount):
        self.bal -= amount
        print("Rs",amount, "was debit")
        print("total balance =",self.get_balance())

    def credit(self,amount):
        self.bal -= amount
        print("Rs",amount, "was credit")
        print("total balance =",self.get_balance())

    def get_balance(self):
        return self.balance

acc1 = Account(100000,12345)
print(acc1.balance)
print(acc1.account_no)

100000
12345


In [3]:
class Account:
    def __init__(self,bal,acc):
        self.balance =bal
        self.account_no =acc

    def debit(self,amount):
        self.balance -= amount
        print("Rs",amount, "was debit")
        print("total balance =",self.get_balance())

    def credit(self,amount):
        self.balance += amount
        print("Rs",amount, "was credit")
        print("total balance =",self.get_balance())

    def get_balance(self):
        return self.balance

acc1 = Account(10000,12345)
acc1.debit(1000)
acc1.credit(500)
a= acc1.get_balance()
print("your total balance is :",a)

Rs 1000 was debit
total balance = 9000
Rs 500 was credit
total balance = 9500
your total balance is : 9500


In [65]:
class student:
    def __init__(self,name):
        self.name = name

s1 = student("mohan")
print(s1.name)
del s1.name
print(s1.name)


mohan


AttributeError: 'student' object has no attribute 'name'

In [71]:
### public password
class Account:
    def __init__(self,acc_no,acc_pass):
        self.acc_no =acc_no
        self.acc_pass =acc_pass

acc1 = Account(12345,"abcde")
print(acc1.acc_no)
print(acc1.__acc_pass)#private acc pass


12345


AttributeError: 'Account' object has no attribute '__acc_pass'

In [83]:
##private password
class Account:
    def __init__(self,acc_no,acc_pass):
        self.acc_no =acc_no
        self.__acc_pass =acc_pass

    def reset_pass(self):
        print(self.__acc_pass)

acc1 = Account("12345","abcde")

print(acc1.acc_no)
print(acc1.reset_pass())



12345
abcde
None


In [7]:
####INHERITANCE
#single inhritance 
class car:
    @staticmethod
    def start():
        print("car start")

    @staticmethod
    def stop():
        print("car stop")

class Toyotacar(car):
    def __init__(self,name):
        self.name = name

car1 = Toyotacar ("fortuner")
car2 = Toyotacar("prince")
print(car1.start())
    

car start
None


In [9]:
## multi - level inheritance(one parents,multiple child)
class car:
    @staticmethod
    def start ():
        print("car start")

    @staticmethod
    def stop():
        print("car stop")

class ToyotaCar(car):
    def __init__(self,brand):
       self.brand =brand

class Fortuner(ToyotaCar):
    def __init__(self,type):
        self.type = type

cae1 = Fortuner("diesel")
car1.start()
    
    

car start


In [13]:
###multiple inheritance(one child ,multiple parents)
class A:
    varA = "welcometo cass A"

class B:
    varB = "welcOme to class B"

class C(A,B):
    varC = "welcome to class C"

c1 =C()
print(c1.varC)
print(c1.varB)
print(c1.varA)



welcome to class C
welcOme to class B
welcometo cass A


In [22]:
class car:
    def __init__(self,type):
        self.type = type

    @staticmethod
    def start():
        print("car start")

    @staticmethod
    def stop():
        print("car stop")

class ToyotaCar(car):
    def __init__(self,name,type):
        self.name = name
        super().__init__(type)
        super().start()
car1 =  ToyotaCar("prius","electric")
print(car1.type)

car start
electric


In [32]:
#######POLYMORPHPISM(one name but have a different signature)
print(2+4) 
print("srm"+"college")
print([1,2,3]+[4,5,6])


6
srmcollege
[1, 2, 3, 4, 5, 6]


In [10]:
import numpy as np

In [15]:

a=np.array([1,2,4,5,7,9],dtype="int")
print(a.mean())
print(np.average(a))
print(np.median(a))
print(3*np.median(a) - 2* np.mean(a))

4.666666666666667
4.666666666666667
4.5
4.166666666666666


In [16]:
#variennce
a= np.array([1,2,3,4,5])
var= np.var(a)
std = np.std(a)
print(var)
print(std)

2.0
1.4142135623730951


In [20]:
a= np.array([1,2,3,4,5])
print(a-3)
print(a.size)



[-2 -1  0  1  2]
5


In [25]:
a= np.array([1,2,3,4,5])
m = np.mean(a)
print(a)
s= (a-m)
print(s)
sq = s**2
print(sq)
var = sq.sum()/a.size
print(var)

[1 2 3 4 5]
[-2. -1.  0.  1.  2.]
[4. 1. 0. 1. 4.]
2.0


In [24]:
print(((a-np.mean(a))**2).sum()/a.size)
print(a.size)

2.0
5


In [30]:
##polynomial
#2x+3y =5
#x+y =2
A=np.array([[2,3],[1,1]],dtype='int')
B=np.array([5,2],dtype='int')
#a-1.dot(B)
inv_A = np.linalg.inv(A)
x= inv_A.dot(B)
print(x)

[1. 1.]


In [57]:
a = np.zeros((4,4) , dtype='int')
a[::2,::2]=1
a[1::2,1::2]=1
print(a)


[[1 0 1 0]
 [0 1 0 1]
 [1 0 1 0]
 [0 1 0 1]]


In [60]:
a = np.zeros((4,4) , dtype='int')
a[1::2,::2]=1
a[0::2,1::2]=1
print(a)

[[0 1 0 1]
 [1 0 1 0]
 [0 1 0 1]
 [1 0 1 0]]


In [61]:
a= np.array([[1,2,3,4],[6,5,7,8]])
m =np.mean(a,axis=0)
print(m)

[3.5 3.5 5.  6. ]


In [62]:
a= np.array([[1,2,3,4],[6,5,7,8]])
m =np.nanmean(a)
print(m)

4.5


In [65]:
#frequency of no.in array
a = np.array([1,2,3,5,6,1,2,3,5,1])
fre= np.bincount(a)
print(fre)
print(fre[5])

[0 3 2 2 0 2 1]
2
