Numpy

In [5]:
import numpy as np
x = np.array([1,2,3,4])
print(x)
print(type(x))

[1 2 3 4]
<class 'numpy.ndarray'>


In [6]:
y = [1,2,3,4]
print(y)
print(type(y))

[1, 2, 3, 4]
<class 'list'>


In [10]:
x= np.array([1,2,3,4,5])
print(x[2]+x[3])

7


In [4]:
a= np.array([[1,2,3,4,5]])
print(a.ndim)

2


In [6]:
a= np.array([[1,2,4,5],[2,3,8,9]])
print(a.ndim)
print(a)

2
[[1 2 4 5]
 [2 3 8 9]]


In [8]:
####making array
z= np.zeros((5,7))
print(z)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


In [9]:
z= np.ones((5,7))
print(z)

[[1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]


In [22]:
z= np.full((5,7),6,dtype='float')
print(z)

[[6. 6. 6. 6. 6. 6. 6.]
 [6. 6. 6. 6. 6. 6. 6.]
 [6. 6. 6. 6. 6. 6. 6.]
 [6. 6. 6. 6. 6. 6. 6.]
 [6. 6. 6. 6. 6. 6. 6.]]


In [15]:
r = np.arange(2,15,2)
print(r)

[ 2  4  6  8 10 12 14]


In [20]:
###indexing
z = np.full((2,15,2),6,dtype='float')
print(z)

[[[6. 6.]
  [6. 6.]
  [6. 6.]
  [6. 6.]
  [6. 6.]
  [6. 6.]
  [6. 6.]
  [6. 6.]
  [6. 6.]
  [6. 6.]
  [6. 6.]
  [6. 6.]
  [6. 6.]
  [6. 6.]
  [6. 6.]]

 [[6. 6.]
  [6. 6.]
  [6. 6.]
  [6. 6.]
  [6. 6.]
  [6. 6.]
  [6. 6.]
  [6. 6.]
  [6. 6.]
  [6. 6.]
  [6. 6.]
  [6. 6.]
  [6. 6.]
  [6. 6.]
  [6. 6.]]]


In [29]:
###indeing
a= np.array([[2,3],[4,5]])
print(a[0,1])


3


In [30]:
##slicing
r = np.arange(2,15,2)
print(r)
print(r[1::2])

[ 2  4  6  8 10 12 14]
[ 4  8 12]


In [32]:
##slicing 2-D arrray
a = np.array([[2,4,7,9],[11,15,2,8]])
print(a[0,1::2])
print(a)

[4 9]
[[ 2  4  7  9]
 [11 15  2  8]]


In [33]:
##swap columnn
a=np.array([[5,3,1],[2,4,6],[8,2,6]])
a[::,2::-2]=a[::,0::2]
print(a)

[[1 3 5]
 [6 4 2]
 [6 2 8]]


In [34]:
##view
a=  np.array([[5,3,1],[2,4,6],[8,2,6]])
b = a.view()
a[0,0]=8
print(a)
print(b)

[[8 3 1]
 [2 4 6]
 [8 2 6]]
[[8 3 1]
 [2 4 6]
 [8 2 6]]


In [37]:
##copy
a=  np.array([[5,3,1],[2,4,6],[8,2,6]])
b = a.copy()
a[0,0]=8
print(a)
print(b)

[[8 3 1]
 [2 4 6]
 [8 2 6]]
[[5 3 1]
 [2 4 6]
 [8 2 6]]


In [43]:
#reshape
##covert 1-d to 2-d
f = np.arange(1,13,2).reshape((2,3))
print(f)

[[ 1  3  5]
 [ 7  9 11]]


In [49]:
#loop
f = np.arange(1,13,2).reshape((1,2))
print(f)
for i in f:
    for j in i:
         print(j,end=" ")
         print(end="\n")

ValueError: cannot reshape array of size 6 into shape (1,2,4)

In [50]:
a=np.array([[2,3,4],[9,0,11]])
for i in np.nditer(a):
    print(i)

2
3
4
9
0
11


In [52]:
a=np.array([[2,3,4],[9,0,11]])
for idx,val in np.ndenumerate(a):
    print(idx,val)

(0, 0) 2
(0, 1) 3
(0, 2) 4
(1, 0) 9
(1, 1) 0
(1, 2) 11


In [58]:
##cncat two arraya  
a= np.array([[2,3,4],[9,0,11]])
b= np.array([[5,7,4],[13,0,11]])
c= np.stack((a,b),axis=0)
print(c)

[[[ 2  3  4]
  [ 9  0 11]]

 [[ 5  7  4]
  [13  0 11]]]


In [59]:
## append
a= np.arange(1,10)
a= np.append(a,[5,1,12])
print(a)

[ 1  2  3  4  5  6  7  8  9  5  1 12]


In [61]:
###soting of array
a= np.array([2,14,10,18,2,7,16,9,4])
a = np.sort(a)
print(a)

[ 2  2  4  7  9 10 14 16 18]


In [63]:
##2d array sorting
a= np.array([[2,3,4],[9,0,11]])
a= np.sort(a,axis=0)
print(a)

[[ 2  0  4]
 [ 9  3 11]]


In [67]:
#####matrix and manipulaion
a= np.array([[2,3,4],[9,0,11]])
b= np.array([[5,13,9],[8,10,15]])
print(a+b)

[[ 7 16 13]
 [17 10 26]]


In [68]:
a= np.array([[2,3,4],[9,0,11]])
b= np.array([[5,13,9],[8,10,15]])
print(a*b)

[[ 10  39  36]
 [ 72   0 165]]


In [6]:
##cros product
a= np.array([[2,3,4],[9,0,11]])
b= np.array([[5,13,9],[8,10,15]])
print(np.cross(a,b))

[[ -25    2   11]
 [-110  -47   90]]


In [7]:
##tranpose matrix
a= np.array([[2,3,4],[9,0,11]])
print(np.transpose(a))

[[ 2  9]
 [ 3  0]
 [ 4 11]]


In [11]:
###trace
a= np.array([[2,3,4],[9,0,11]])
print(np.trace(a))

2


In [ ]:
###liniar algebra


In [12]:
##searching - where
a= np.arange(1,50,8)
print(a)
print(np.where(a==41))

[ 1  9 17 25 33 41 49]
(array([5], dtype=int64),)


In [ ]:
##searching
a= np.array([41,41,51])
prinr(a)
print(np.where(a))

In [ ]:
##string array ## np char
a= np.array(['a','b'])
print(a.)